startTime = 0
Link_Exists_path = '../Bands15/1/'
DataMule_path = '../Lexington15/1/Day1/'
metrics_file_name = 'metrics_epidemic.txt'
delivery_file_name = 'delivered_messages_epidemic.txt'
generated_file_name = "generated_messages_epidemic.txt"
notDelivered_file_name = "not_delivered_messages_epidemic.txt"
max_nodes = 15
M = [1, 10, 25, 50, 100, 500, 750, 1000]
maxTau = 10
num_messages = 500
num_sources = 8
num_des = 4
T = 90
tau = 1
t_sd = 0.5
t_td = 1
idle_channel_prob = 0.5
